name: Deploy SIA to VPS

on:
  push:
    branches: [ main ]   # cambia si despliegas desde otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # PHP para Composer (solo si hay composer.json)
      - name: Setup PHP
        if: ${{ hashFiles('composer.json') != '' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, pdo_mysql, curl, gd, zip
          tools: composer

      - name: Install PHP dependencies (Composer)
        if: ${{ hashFiles('composer.json') != '' }}
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # Node para build de assets (solo si hay package.json)
      - name: Setup Node
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build assets
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          if npm run | grep -q "build"; then npm run build; fi


      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          if [ -n "${{ secrets.SIA_SSH_KEY_B64 }}" ]; then
            echo "${{ secrets.SIA_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/gha_sia
          else
            printf '%s' "${{ secrets.SIA_SSH_KEY }}" | tr -d '\r' > ~/.ssh/gha_sia
          fi
          chmod 600 ~/.ssh/gha_sia
          ssh-keyscan -p 3500 174.136.26.185 >> ~/.ssh/known_hosts

      - name: Inspect SSH key on runner
        run: |
          set -eu
          echo 'First & last lines of key:'
          sed -n '1p;$p' ~/.ssh/gha_sia || true
          echo 'File type:'
          file ~/.ssh/gha_sia || true
          echo 'Keygen -y check:'
          if ssh-keygen -y -f ~/.ssh/gha_sia >/dev/null 2>&1; then echo OK; else echo FAIL; fi

      - name: Test SSH connectivity (verbose)
        run: |
          ssh -vvv -i ~/.ssh/gha_sia -p 3500 -o IdentitiesOnly=yes \
            -o BatchMode=yes -o StrictHostKeyChecking=no \
            calientes@174.136.26.185 'echo ok-ssh'

      - name: Rsync to server
        run: |
          RSYNC_FLAGS="-az --delete \
            --exclude .git --exclude .github \
            --exclude node_modules --exclude '*.log'"
          DEST="calientes@174.136.26.185:/home/calientes/domains/serviciosinmobiliariosaguascalientes.com/public_html/"
          rsync $RSYNC_FLAGS -e "ssh -i ~/.ssh/gha_sia -p 3500 -o IdentitiesOnly=yes" ./ "$DEST"